name: af3-env
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - hmmer=3.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
