name: af3-env
channels:
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - hmmer=3.4=hdbdd923_2
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - python=3.11.10=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  # - pip:
  #     - absl-py==2.1.0
  #     - chex==0.1.87
  #     - dm-haiku==0.0.13
  #     - dm-tree==0.1.8
  #     - filelock==3.16.1
  #     - jax==0.4.35
  #     - jax-cuda12-pjrt==0.4.35
  #     - jax-cuda12-plugin==0.4.35
  #     - jax-triton==0.2.0
  #     - jaxlib==0.4.34
  #     - jaxtyping==0.2.34
  #     - jmp==0.0.4
  #     - ml-dtypes==0.5.0
  #     - numpy==2.1.3
  #     - nvidia-cublas-cu12==12.6.3.3
  #     - nvidia-cuda-cupti-cu12==12.6.80
  #     - nvidia-cuda-nvcc-cu12==12.6.77
  #     - nvidia-cuda-runtime-cu12==12.6.77
  #     - nvidia-cudnn-cu12==9.5.1.17
  #     - nvidia-cufft-cu12==11.3.0.4
  #     - nvidia-cusolver-cu12==11.7.1.2
  #     - nvidia-cusparse-cu12==12.5.4.2
  #     - nvidia-nccl-cu12==2.23.4
  #     - nvidia-nvjitlink-cu12==12.6.77
  #     - opt-einsum==3.4.0
  #     - pillow==11.0.0
  #     - pip==24.3.1
  #     - rdkit==2024.3.5
  #     - scipy==1.14.1
  #     - tabulate==0.9.0
  #     - toolz==1.0.0
  #     - tqdm==4.67.0
  #     - triton==3.1.0
  #     - typeguard==2.13.3
  #     - typing-extensions==4.12.2
  #     - zstandard==0.23.0
# prefix: /ibex/user/zhac/software/miniconda3/envs/af3
